version: '3.6'
networks:
  default:
    name: swe5003-network
    external: true
services:
  stream:
      build:
        context: ../../../src/streaming/
      container_name: stream
      command: python producer.py
      working_dir: /home/streaming
      volumes:
        - ./streaming:/home/stream_pipeline
      environment:
        PYTHONUNBUFFERED: 1